export const FETCH_POKEMONS = 'FETCH_POKEMONS';
export const FETCH_CACHED_POKEMONS = 'FETCH_CACHED_POKEMONS';
export const FETCH_UNCACHED_POKEMONS = 'FETCH_UNCACHED_POKEMONS';
export const FETCH_POKEMON = 'FETCH_POKEMON';
export const ADD_STORAGE = 'ADD_STORAGE';
export const REMOVE_STORATE = 'REMOVE_STORAGE';