export const FETCH_CACHED_POKEMONS = 'FETCH_CACHED_POKEMONS';
export const FETCH_UNCACHED_POKEMONS = 'FETCH_UNCACHED_POKEMONS';
export const FETCH_POKEMON_DETAIL = 'FETCH_POKEMON_DETAIL';
export const CATCH_POKEMON = 'CATCH_POKEMON';
export const RELEASE_POKEMON = 'RELEASE_POKEMON';